version: "2"

services:
  app:
    container_name: voucher
    image: voucher:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    links:
      - redis
    environment:
      REDIS_HOST: 'redis:6379'
      REDIS_DB: 0
  redis:
    container_name: voucher-redis
    image: redis
    logging:
      driver: none
