// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/entities.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Voucher struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Brand                string   `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ExpiresAt            string   `protobuf:"bytes,6,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Voucher) Reset()         { *m = Voucher{} }
func (m *Voucher) String() string { return proto.CompactTextString(m) }
func (*Voucher) ProtoMessage()    {}
func (*Voucher) Descriptor() ([]byte, []int) {
	return fileDescriptor_0997e8085c51a3c1, []int{0}
}

func (m *Voucher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Voucher.Unmarshal(m, b)
}
func (m *Voucher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Voucher.Marshal(b, m, deterministic)
}
func (m *Voucher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Voucher.Merge(m, src)
}
func (m *Voucher) XXX_Size() int {
	return xxx_messageInfo_Voucher.Size(m)
}
func (m *Voucher) XXX_DiscardUnknown() {
	xxx_messageInfo_Voucher.DiscardUnknown(m)
}

var xxx_messageInfo_Voucher proto.InternalMessageInfo

func (m *Voucher) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Voucher) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Voucher) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Voucher) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Voucher) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Voucher) GetExpiresAt() string {
	if m != nil {
		return m.ExpiresAt
	}
	return ""
}

func init() {
	proto.RegisterType((*Voucher)(nil), "pb.Voucher")
}

func init() { proto.RegisterFile("pb/entities.proto", fileDescriptor_0997e8085c51a3c1) }

var fileDescriptor_0997e8085c51a3c1 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xcf, 0xbb, 0x6e, 0xc3, 0x20,
	0x14, 0xc6, 0x71, 0x99, 0xda, 0xae, 0xcc, 0x50, 0xa9, 0xa8, 0x03, 0x43, 0x87, 0x5c, 0x96, 0x4c,
	0x66, 0xc8, 0x13, 0x38, 0x6b, 0x36, 0x0f, 0x19, 0xb2, 0x71, 0x39, 0x8a, 0x91, 0x62, 0x40, 0xf8,
	0xd8, 0xca, 0x8b, 0xe4, 0x7d, 0x23, 0x83, 0x94, 0x6c, 0x7c, 0xbf, 0xff, 0xc2, 0xa1, 0xbf, 0x41,
	0x09, 0x70, 0x68, 0xd1, 0xc2, 0xd4, 0x86, 0xe8, 0xd1, 0x33, 0x12, 0xd4, 0xee, 0x59, 0xd0, 0xef,
	0x8b, 0x9f, 0xf5, 0x00, 0x91, 0xfd, 0x50, 0x62, 0x0d, 0x2f, 0x36, 0xc5, 0xa1, 0xe9, 0x89, 0x35,
	0x8c, 0xd1, 0xd2, 0xc9, 0x11, 0x38, 0x49, 0x92, 0xde, 0xec, 0x8f, 0x56, 0x2a, 0x4a, 0x67, 0xf8,
	0x57, 0xc2, 0x3c, 0x56, 0x5d, 0xe4, 0x7d, 0x06, 0x5e, 0x66, 0x4d, 0x83, 0xfd, 0xd3, 0x46, 0x47,
	0x90, 0x08, 0xa6, 0x43, 0x5e, 0xa5, 0xf2, 0x81, 0xb5, 0xc2, 0x23, 0xd8, 0x08, 0x53, 0x87, 0xbc,
	0xce, 0xf5, 0x0d, 0xa7, 0xfd, 0x75, 0x7b, 0xb3, 0x38, 0xcc, 0xaa, 0xd5, 0x7e, 0x14, 0xbd, 0xd5,
	0x83, 0x8c, 0xe6, 0xec, 0x7c, 0x10, 0x4b, 0xfe, 0xad, 0x08, 0x4a, 0xd5, 0xe9, 0x8e, 0xe3, 0x2b,
	0x00, 0x00, 0xff, 0xff, 0x34, 0xb0, 0xc4, 0xeb, 0xdc, 0x00, 0x00, 0x00,
}
